# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
  - stage: Fan out
    jobs:
      - job: A
        steps:
        - script: echo Stage fan out job A
          
      - job: B
        dependsOn: A
        steps:
          - bash: echo "job B depends on Job A"
      
      - job: C
        dependsOn: A
        steps:
          - script: echo "job c depende on job A"

